# Generated by Django 5.0.6 on 2024-06-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_status',
            field=models.ForeignKey(blank=True, db_column='leave_status_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.status'),
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='leave_status',
            new_name='leave_status_id',
        ),
    ]
