# Generated by Django 5.0.6 on 2024-06-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_leave_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeID', to='employee.employee')),
                ('supervisor_id', models.OneToOneField(db_column='supervisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorID', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Reporting',
                'verbose_name_plural': 'Reporting',
                'db_table': 'reporting',
            },
        ),
    ]
