# Generated by Django 5.0.6 on 2024-06-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_department_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.department'),
        ),
    ]
